module.exports = {
	preset: 'ts-jest',
	rootDir: '.',
	roots: ['src'],
	setupFilesAfterEnv: ['src/tests/setup.ts'],
	collectCoverageFrom: [
		'src/**/*.{js,jsx,ts,tsx}',
		'!src/**/*.d.ts',
		'!src/server.ts',
		'!src/logger.ts',
		'!src/enums/**',
	],
	runner: 'groups',
	testMatch: [
		'src/tests/**/*.test.{js,jsx,ts,tsx}',
		'src/integration-tests/**/*.test.{js,jsx,ts,tsx}',
	],
	testEnvironment: 'node',
	testResultsProcessor: 'jest-sonar-reporter',
	transformIgnorePatterns: ['^.+\\.module\\.(css|sass|scss)$'],
	moduleFileExtensions: ['js', 'ts', 'tsx', 'jsx', 'node', 'json'],
	resetMocks: true,
	restoreMocks: true,
	workerIdleMemoryLimit: '512MB',
};
